// app/layout.tsx
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './providers' // Import Providers
import { Toaster as SonnerToaster } from "@/components/ui/sonner" // Import Sonner

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Kanaka Engagement App', // Update title
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers> {/* Wrap children */}
          {children}
          <SonnerToaster richColors position="top-right" /> {/* Add Sonner */}
        </Providers>
      </body>
    </html>
  )
} 